language: java
jdk:
  - openjdk12

addons:
  sonarcloud:
    organization: "meronbrouwer-github"

services:
  - xvfb

after_success:
  - mvn jacoco:prepare-agent install jacoco:report sonar:sonar coveralls:report
  - mvn compile javadoc:javadoc
#  - mvn install:install-file -Dfile=target/yaeger-shadyjar.jar -DgroupId=nl.han.ica -DartifactId=yaeger-shadyjar -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true

deploy:
    provider: pages
    local-dir: target/site/apidocs
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master
