[book]
authors = ["Meron Brouwer"]
description = "A Java based 2D Game Engine, focused on an Object Oriented style of programming"
language = "en"
multilingual = false
src = "docs"
title = "Yaeger"

[build]
build-dir = "target/docs"
create-missing = false

[output.html]
git-repository-url = "https://github.com/han-yaeger/yaeger"
